credentials:
  usernames:
    selepand@cisco.com:
      name: Sravan Kumar E
      password: $2b$12$Xy84zbiUf6YjPdhSLDHcZ.8rEnQ4KXZbGmpAjOrF1OiDdrz7s.lZy
      role: Admin
    john@doe.com:
      name: John Doe
      password: $2b$12$QFZcZyffXo7t85w8hOcQdOq3/EKlh0aXb5b6PGq3jzn5ppGW6CzQS
      role: Registered

cookie:
  name: aiassethub
  key: some_signature_key
  expiry_days: 30
